### ISSUE TITLE
Failed to load ApplicationContext after update to 1.4.0

### ISSUE THREAD

**Issue by tloszabno** [micrometer-metrics/micrometer#1956]
I use spring boot 2.2.5-RELEASE, after update a micrometer-registry-new-relic from 1.3.5 to 1.4.0 my application does not start.

Stacktrace:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'newRelicMeterRegistry' defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/export/newrelic/NewRelicMetricsExportAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.micrometer.newrelic.NewRelicMeterRegistry]: Factory method 'newRelicMeterRegistry' threw exception; nested exception is java.lang.NoSuchMethodError: 'io.micrometer.newrelic.NewRelicMeterRegistry$Builder io.micrometer.newrelic.NewRelicMeterRegistry$Builder.httpClient(io.micrometer.core.ipc.http.HttpSender)'
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789)
	... 193 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.micrometer.newrelic.NewRelicMeterRegistry]: Factory method 'newRelicMeterRegistry' threw exception; nested exception is java.lang.NoSuchMethodError: 'io.micrometer.newrelic.NewRelicMeterRegistry$Builder io.micrometer.newrelic.NewRelicMeterRegistry$Builder.httpClient(io.micrometer.core.ipc.http.HttpSender)'
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
	... 207 more
Caused by: java.lang.NoSuchMethodError: 'io.micrometer.newrelic.NewRelicMeterRegistry$Builder io.micrometer.newrelic.NewRelicMeterRegistry$Builder.httpClient(io.micrometer.core.ipc.http.HttpSender)'
	at org.springframework.boot.actuate.autoconfigure.metrics.export.newrelic.NewRelicMetricsExportAutoConfiguration.newRelicMeterRegistry(NewRelicMetricsExportAutoConfiguration.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 208 more
```
It seems that you removed the method which is used by spring boot in autoconfiguration for plugin. Backward compatibility is broken now:
`NewRelicMetricsExportAutoConfiguration`:
```java
@Bean
  @ConditionalOnMissingBean
  public NewRelicMeterRegistry newRelicMeterRegistry(NewRelicConfig newRelicConfig, Clock clock) {
    return NewRelicMeterRegistry.builder(newRelicConfig).clock(clock).httpClient(new HttpUrlConnectionSender(this.properties.getConnectTimeout(), this.properties.getReadTimeout())).build();
  }
```

**Comment by shakuzen** [comment]
Thank you for the report. We'll add back that method to not break API compatibility. Spring Boot will also have some corresponding changes when they upgrade the version of Micrometer they manage, but we should make as smooth a transition as possible.

**Comment by shakuzen** [comment]
@tloszabno would you be able to try with the latest 1.4.2-SNAPSHOT version and let us know if that resolves the issue?

**Comment by tloszabno** [comment]
@shakuzen hello, I've just tested it - all works fine - thanks for fix!
