### PR TITLE
Add back httpClient method to NewRelicMeterRegistry Builder

### LINKED ISSUE #1956: Failed to load ApplicationContext after update to 1.4.0
I use spring boot 2.2.5-RELEASE, after update a micrometer-registry-new-relic from 1.3.5 to 1.4.0 my application does not start.

Stacktrace:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'newRelicMeterRegistry' defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/export/newrelic/NewRelicMetricsExportAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.micrometer.newrelic.NewRelicMeterRegistry]: Factory method 'newRelicMeterRegistry' threw exception; nested exception is java.lang.NoSuchMethodError: 'io.micrometer.newrelic.NewRelicMeterRegistry$Builder io.micrometer.newrelic.NewRelicMeterRegistry$Builder.httpClient(io.micrometer.core.ipc.http.HttpSender)'
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789)
	... 193 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.micrometer.newrelic.NewRelicMeterRegistry]: Factory method 'newRelicMeterRegistry' threw exception; nested exception is java.lang.NoSuchMethodError: 'io.micrometer.newrelic.NewRelicMeterRegistry$Builder io.micrometer.newrelic.NewRelicMeterRegistry$Builder.httpClient(io.micrometer.core.ipc.http.HttpSender)'
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
	... 207 more
Caused by: java.lang.NoSuchMethodError: 'io.micrometer.newrelic.NewRelicMeterRegistry$Builder io.micrometer.newrelic.NewRelicMeterRegistry$Builder.httpClient(io.micrometer.core.ipc.http.HttpSender)'
	at org.springframework.boot.actuate.autoconfigure.metrics.export.newrelic.NewRelicMetricsExportAutoConfiguration.newRelicMeterRegistry(NewRelicMetricsExportAutoConfiguration.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 208 more
```
It seems that you removed the method which is used by spring boot in autoconfiguration for plugin. Backward compatibility is broken now:
`NewRelicMetricsExportAutoConfiguration`:
```java
@Bean
  @ConditionalOnMissingBean
  public NewRelicMeterRegistry newRelicMeterRegistry(NewRelicConfig newRelicConfig, Clock clock) {
    return NewRelicMeterRegistry.builder(newRelicConfig).clock(clock).httpClient(new HttpUrlConnectionSender(this.properties.getConnectTimeout(), this.properties.getReadTimeout())).build();
  }
```

### PR DESCRIPTION
**Pull request by shakuzen**
This preserves backwards compatibility with previous versions while deprecating the method. An alternate way to customize the `HttpSender` is available now via the `clientProvider` method.

Fixes #1956

### CODE REVIEW

**Comment by shakuzen** [comment]
/cc @neiljpowell 
Adding the tests for this made me realize we're in a similar situation with the `namingConvention` method on the Builder, because the `NewRelicClientProvider` implementations can also take a naming convention. This is a bit of a hairy setup in that it differs from how other MeterRegistry builders/configuration work. See also #1958.

File: implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java [hunk 1]
```diff
@@ -134,7 +139,26 @@ public Builder threadFactory(ThreadFactory threadFactory) {
...
+            return this;
+        }
+
         public NewRelicMeterRegistry build() {
+            if (clientProvider == null && httpClient != null) {
+                //default to Insight API client provider if not specified in config or provided
+                clientProvider = (config.clientProviderType() == ClientProviderType.INSIGHTS_AGENT)
+                        ? new NewRelicInsightsAgentClientProvider(config)
+                        : new NewRelicInsightsApiClientProvider(config, httpClient, convention);
+            }
```
Comment (neiljpowell) [inline implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java:161]: Adding "&& httpClient != null" to condition won't allow config to specify Agent provider. The httpClient check should be in an inner condition that drives which API Client provider constructor to use.  An inner condition enables support for .builder(config).build(); and .builder(config).httpClient(httpClient).build(); for API publishing.

Comment (shakuzen) [reply implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java:161]: I'm sure there's still some simplification possible, but I'm not understanding the current issue. Could you share a test that shows what's not working now? If the agent provider is configured in `NewRelicConfig`, then either 
A) the `clientProvider` will be set in this if block (if `httpClient` is also set - which won't be used for the agent provider)
or
B) `clientProvider` will remain `null` and the `NewRelicMeterRegistry` constructor will instantiate the `NewRelicInsightsAgentClientProvider`

Comment (neiljpowell) [reply implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java:161]: Ah, I wasn't taking into account the `NewRelicMeterRegistry` constructor behavior.  I was thinking that if `httpClient` was set, that the condition would be more clear if only the `NewRelicInsightsApiClientProvider` was used, from a pure backward compatibility perspective with Boot 2.2.x (config clientProviderType ignored).  Your approach also allows use of the Agent provider.
