### ISSUE TITLE
1.3.x and 1.4.x not compatible

### ISSUE THREAD

**Issue by anuraaga** [micrometer-metrics/micrometer#2002]
I noticed https://github.com/micrometer-metrics/micrometer/commit/3da05bbb8a66371f6e01ecb5963497e2b4850147 has a backwards incompatible change of the return type from `Long getMaximumExpectedValue()` to `Double getMaximumExpectedValue()`. Since micrometer uses semantic versioning, as documented at https://micrometer.io/docs/support, I guess this wasn't intended?

Because of the change, all Armeria users are locked into 1.3.x, and if a library targeted 1.4.x and used a new API, it would be impossible to use this library with Armeria without asking it to downgrade, possibly losing some monitoring features. For reference, this change downgraded Armeria's dependency from 1.4.x to 1.3.x, requiring code change since they are not API or ABI compatible.

https://github.com/line/armeria/commit/890631e15dff9b7030f20b18649d461e3efb5b34#diff-c966b7c3ea79ab16c67724170ff57f47R115

I understand that 1.4.x is not LTS, but I guess that doesn't preclude it from actually being used, it's more about whether it gets patch updates or not. But with this API break, more and more users will be unable to use it due to the API mismatch.

Unfortunately 1.4.x is released, but do you think we can add a method to both 1.3.x and 1.4.x, `getMaximumExpectedValueAsDouble` to provide libraries a way to work with both versions?

**Comment by shakuzen** [comment]
Just something that came to mind, here's a hack I think should work with 1.3.x and 1.4.x:

```java
Long someLong = (distributionStatisticConfig.getMaximumExpectedValue() == null) ? null : ((Number) distributionStatisticConfig.getMaximumExpectedValue()).longValue();
Double someDouble = distributionStatisticConfig.getMinimumExpectedValue() == null ? null : ((Number) distributionStatisticConfig.getMinimumExpectedValue()).doubleValue();
```

**Comment by anuraaga** [comment]
I would have to try to make sure, but pretty sure it doesn't work since `Long` vs `Double` are not ABI compatible so the method call itself will crash with `NoSuchMethodError`

```
'java.lang.Long io.micrometer.core.instrument.distribution.DistributionStatisticConfig.getMaximumExpectedValue()'
java.lang.NoSuchMethodError: 'java.lang.Long io.micrometer.core.instrument.distribution.DistributionStatisticConfig.getMaximumExpectedValue()'
	at com.linecorp.armeria.common.metric.MoreMeters.newTimer(MoreMeters.java:115)
```

**Comment by shakuzen** [comment]
Alright. Although we'll have to introduce some stuff to bridge compatibility (thanks for the pull requests, by the way), I'd like to get back to a state of a single method (ideally named without `asX`) per single purpose in as few releases while allowing compatibility between at least adjacent minor versions (conservatively, LTS minor versions). I'm proposing the following plan (using the getMin method as an example):

| 1.1.x | 1.3.8+ | 1.4.2+ ^ | 1.5.x | Next LTS | Next next LTS |
| -- | -- | -- | -- | -- | -- |
| <li>Long getMin</li> | <li>~Long getMin~</li><li>Double getMinAsD</li> | <li>~Double getMin~</li><li>Double getMinAsD</li> | <li>~Double getMin~</li><li>Double getMinAsD</li> | <li>Double getMin</li><li>~Double getMinAsD~</li> | <li>Double getMin</li> |

^ non-LTS minor
~deprecated~

What do you think? Does this seem like a reasonable plan to get things back to a good state while allowing libraries like Armeria to be compatible with a range of Micrometer versions?

**Comment by anuraaga** [comment]
Agree getting to one method is importany and the plan looks fine to me. But I guess we should clarify, I guess next-next LTS here will be 2.x since it removes the API and semantic versioning?

**Comment by shakuzen** [comment]
This should be resolved now thanks to @anuraaga's pull requests. Please check snapshots and let me know if not. We'll be releasing patch versions soon.
